openapi: 3.0.3
info:
  title: TMDB API
  description: The Movie Database (TMDB) API
  version: 0.15.0
servers:
  - url: 'https://api.themoviedb.org/3'
tags:
  - name: Configuration
  - name: Genre
  - name: Keywords
  - name: Movie Lists
  - name: Movies
  - name: Search
paths:
  /configuration:
    get:
      summary: Details
      description: Query the API configuration details.
      operationId: ConfigurationDetails
      tags:
        - Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: object
                    properties:
                      base_url:
                        type: string
                        example: 'http://image.tmdb.org/t/p/'
                      secure_base_url:
                        type: string
                        example: 'https://image.tmdb.org/t/p/'
                      backdrop_sizes:
                        type: array
                        items:
                          type: string
                          example: w300
                      logo_sizes:
                        type: array
                        items:
                          type: string
                          example: w45
                      poster_sizes:
                        type: array
                        items:
                          type: string
                          example: w92
                      profile_sizes:
                        type: array
                        items:
                          type: string
                          example: w45
                      still_sizes:
                        type: array
                        items:
                          type: string
                          example: w92
                    required:
                      - base_url
                      - secure_base_url
                      - backdrop_sizes
                      - logo_sizes
                      - poster_sizes
                      - profile_sizes
                      - still_sizes
                  change_keys:
                    type: array
                    items:
                      type: string
                      example: adult
                required:
                  - images
                  - change_keys
        '401':
          $ref: '#/components/responses/Unauthorized'
  /configuration/countries:
    get:
      summary: Countries
      description: Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
      operationId: ConfigurationCountries
      tags:
        - Configuration
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /configuration/jobs:
    get:
      summary: Jobs
      description: Get the list of the jobs and departments we use on TMDB.
      operationId: ConfigurationJobs
      tags:
        - Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
                example:
                  - department: Actors
                    jobs:
                      - Actor
                      - Cameo
                      - Special Guest
                      - Voice
                  - department: Directing
                    jobs:
                      - Director
                      - Other
        '401':
          $ref: '#/components/responses/Unauthorized'
  /configuration/languages:
    get:
      summary: Languages
      description: Get the list of languages (ISO 639-1 tags) used throughout TMDB.
      operationId: ConfigurationLanguages
      tags:
        - Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'
                example:
                  - iso_639_1: en
                    english_name: English
                    name: English
                  - iso_639_1: eo
                    english_name: Esperanto
                    name: Esperanto
        '401':
          $ref: '#/components/responses/Unauthorized'
  /configuration/primary_translations:
    get:
      summary: Primary Translations
      description: Get a list of the officially supported translations on TMDB.
      operationId: ConfigurationPrimaryTranslations
      tags:
        - Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - en-GB
                  - en-US
                  - eo-EO
        '401':
          $ref: '#/components/responses/Unauthorized'
  /configuration/timezones:
    get:
      summary: Timezones
      description: Get the list of timezones used throughout TMDB.
      operationId: ConfigurationTimezones
      tags:
        - Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    iso_3166_1:
                      type: string
                      description: ISO 3166-1 tag
                      minLength: 2
                      maxLength: 2
                      pattern: '^[A-Z]{2}$'
                    zones:
                      type: array
                      items:
                        type: string
                  required:
                    - iso_3166_1
                    - zones
                example:
                  - iso_3166_1: ES
                    zones:
                      - Europe/Madrid
                      - Africa/Ceuta
                      - Atlantic/Canary
                  - iso_3166_1: GB
                    zones:
                      - Europe/London
        '401':
          $ref: '#/components/responses/Unauthorized'
  /genre/movie/list:
    get:
      summary: Movie List
      description: Get the list of official genres for movies.
      operationId: GenreMovieList
      tags:
        - Genre
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
                example:
                  - id: 28
                    name: Action
        '401':
          $ref: '#/components/responses/Unauthorized'
  /genre/tv/list:
    get:
      summary: TV List
      description: Get the list of official genres for TV shows.
      operationId: GenreTvList
      tags:
        - Genre
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
                example:
                  - id: 10759
                    name: Action & Adventure
        '401':
          $ref: '#/components/responses/Unauthorized'
  '/keyword/{keyword_id}':
    get:
      summary: Details
      operationId: KeywordDetails
      tags:
        - Keywords
      parameters:
        - $ref: '#/components/parameters/KeywordID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
              example:
                id: 1701
                name: hero
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  '/keyword/{keyword_id}/movies':
    get:
      summary: Movies
      description: 'This method is deprecated, you should use `/discover/movie` instead.'
      operationId: KeywordMovies
      tags:
        - Keywords
      parameters:
        - $ref: '#/components/parameters/KeywordID'
        - $ref: '#/components/parameters/IncludeAdult'
        - $ref: '#/components/parameters/LanguageParam'
        - $ref: '#/components/parameters/Page'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieListPage'
              example:
                id: 1701
                page: 1
                results:
                  - adult: false
                    backdrop_path: /3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg
                    genre_ids:
                      - 28
                    id: 640146
                    original_language: en
                    original_title: 'Ant-Man and the Wasp: Quantumania'
                    overview: 'Das Superhelden-Duo Scott Lang und Hope Van Dyne erkundet zusammen mit Hopes Eltern Hank Pym und Janet Van Dyne das Quantenreich, interagiert mit seltsamen neuen Kreaturen und begibt sich auf ein Abenteuer, das sie über die Grenzen dessen hinaustreiben wird, was sie für möglich gehalten haben.'
                    popularity: 9200.005
                    poster_path: /nA5otwVxAfpBP4PVgeuBk3qHcLY.jpg
                    release_date: '2023-02-15'
                    title: 'Ant-Man and the Wasp: Quantumania'
                    video: false
                    vote_average: 6.5
                    vote_count: 2079
                total_pages: 11
                total_results: 211
        '400':
          $ref: '#/components/responses/InvalidPage'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      deprecated: true
  /movie/now_playing:
    get:
      summary: Now Playing
      description: |
        Get a list of movies that are currently in theatres.


        > **Note**
        > This call is really just a discover call behind the scenes. If you would like to tweak any of the default
        > filters head over and read about [discover](https://developer.themoviedb.org/reference/discover-movie).
      operationId: MovieNowPlaying
      tags:
        - Movie Lists
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Region'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieListPageWithDates'
              example:
                dates:
                  maximum: '2023-05-03'
                  minimum: '2023-03-16'
                page: 1
                results:
                  - adult: false
                    backdrop_path: /iJQIbOPm81fPEGKt5BPuZmfnA54.jpg
                    genre_ids:
                      - 16
                    id: 502356
                    original_language: en
                    original_title: 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.'
                    popularity: 6572.614
                    poster_path: /qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg
                    release_date: '2023-04-05'
                    title: The Super Mario Bros. Movie
                    video: false
                    vote_average: 7.5
                    vote_count: 1456
                total_pages: 87
                total_results: 1734
  '/movie/{movie_id}/keywords':
    get:
      summary: Keywords
      operationId: MovieKeywords
      tags:
        - Movies
      parameters:
        - $ref: '#/components/parameters/MovieID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  keywords:
                    type: array
                    items:
                      $ref: '#/components/schemas/Object'
                required:
                  - id
                  - keywords
              example:
                id: 550
                keywords:
                  - id: 818
                    name: based on novel or book
  '/movie/{movie_id}/similar':
    get:
      summary: Similar
      description: |
        Get the similar movies based on genres and keywords.


        > **Note**
        > This method only looks for other items based on genres and plot keywords. As such, the results found here
        > are not always going to be perfect. Use it with that in mind.
      operationId: MovieSimilar
      tags:
        - Movies
      parameters:
        - $ref: '#/components/parameters/MovieID'
        - $ref: '#/components/parameters/LanguageParam'
        - $ref: '#/components/parameters/Page'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieListPage'
              example:
                page: 1
                results:
                  - adult: false
                    backdrop_path: /3YAldML4EDyoC6RBpzceALigrAZ.jpg
                    genre_ids:
                      - 18
                    id: 9300
                    original_language: en
                    original_title: Orlando
                    overview: 'England, 1600. Queen Elizabeth I promises Orlando, a young nobleman obsessed with poetry, that she will grant him land and fortune if he agrees to satisfy a very particular request.'
                    popularity: 7.768
                    poster_path: /xvz0qZkXXMq3dH2Revxii8drxWc.jpg
                    release_date: '1992-12-11'
                    title: Orlando
                    video: false
                    vote_average: 6.966
                    vote_count: 262
                total_pages: 364
                total_results: 7269
  /search/keyword:
    get:
      summary: Keyword
      description: Search for keywords by their name.
      operationId: SearchKeyword
      tags:
        - Search
      parameters:
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/Page'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectListPage'
              example:
                page: 1
                results:
                  - id: 262419
                    name: lost
                total_pages: 5
                total_results: 84
        '400':
          $ref: '#/components/responses/InvalidPage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /search/movie:
    get:
      summary: Movie
      description: 'Search for movies by their original, translated and alternative titles.'
      operationId: SearchMovie
      tags:
        - Search
      parameters:
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/IncludeAdult'
        - $ref: '#/components/parameters/LanguageParam'
        - in: query
          name: primary_release_year
          schema:
            type: string
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Region'
        - in: query
          name: year
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieListPage'
              example:
                page: 1
                results:
                  - adult: false
                    backdrop_path: /hZkgoQYus5vegHoetLkCJzb17zJ.jpg
                    genre_ids:
                      - 18
                    id: 550
                    original_language: en
                    original_title: Fight Club
                    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                    popularity: 73.433
                    poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                    release_date: '1999-10-15'
                    title: Fight Club
                    video: false
                    vote_average: 8.433
                    vote_count: 26279
                total_pages: 2
                total_results: 39
        '400':
          $ref: '#/components/responses/InvalidPage'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  parameters:
    IncludeAdult:
      in: query
      name: include_adult
      schema:
        type: boolean
        default: false
    KeywordID:
      in: path
      name: keyword_id
      schema:
        type: integer
        format: int32
      required: true
      description: The keyword ID.
    LanguageParam:
      in: query
      name: language
      schema:
        type: string
        minLength: 2
        maxLength: 5
        pattern: '^([a-z]{2})-([A-Z]{2})$'
        default: en-US
      description: '`ISO-639-1`-`ISO-3166-1` code'
    MovieID:
      in: path
      name: movie_id
      schema:
        type: integer
        format: int32
      required: true
      description: The movie ID.
    Page:
      in: query
      name: page
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 500
        default: 1
    Query:
      in: query
      name: query
      required: true
      schema:
        type: string
    Region:
      in: query
      name: region
      schema:
        type: string
        minLength: 2
        maxLength: 2
        pattern: '^([A-Z]{2})$'
      description: '`ISO-3166-1` code'
  responses:
    InvalidPage:
      description: Invalid page number
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - success: false
              status_code: 22
              status_message: 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.'
    NotFound:
      description: The server can not find the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - success: false
              status_code: 34
              status_message: The resource you requested could not be found.
    Unauthorized:
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - success: false
              status_code: 7
              status_message: 'Invalid API key: You must be granted a valid key.'
  schemas:
    Country:
      type: object
      additionalProperties: false
      properties:
        iso_3166_1:
          type: string
          description: ISO 3166-1 tag
          minLength: 2
          maxLength: 2
          pattern: '^[A-Z]{2}$'
          example: AD
        english_name:
          type: string
          example: Andorra
        native_name:
          type: string
          example: Andorra
      required:
        - iso_3166_1
        - english_name
    Department:
      type: object
      additionalProperties: false
      properties:
        department:
          type: string
          description: The name of the department
        jobs:
          type: array
          items:
            type: string
      required:
        - department
        - jobs
    Error:
      type: object
      properties:
        success:
          type: boolean
        status_code:
          type: integer
          format: int32
          minimum: 1
          maximum: 47
        status_message:
          type: string
      required:
        - success
        - status_code
        - status_message
    Language:
      type: object
      additionalProperties: false
      properties:
        iso_639_1:
          type: string
          description: ISO 3166-1 tag
          minLength: 2
          maxLength: 2
          pattern: '^[a-z]{2}$'
        english_name:
          type: string
        name:
          type: string
      required:
        - iso_639_1
        - english_name
    MovieListItem:
      type: object
      properties:
        id:
          type: integer
          default: 0
        title:
          type: string
        original_language:
          type: string
        original_title:
          type: string
        adult:
          type: boolean
          default: false
        backdrop_path:
          type: string
        genre_ids:
          type: array
          items:
            type: integer
            format: int32
            default: 0
        overview:
          type: string
        popularity:
          type: number
        poster_path:
          type: string
        release_date:
          type: string
        video:
          type: boolean
          default: true
        vote_average:
          type: number
        vote_count:
          type: integer
      required:
        - id
        - title
        - original_language
        - original_title
    MovieListPage:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 1
          maximum: 500
          default: 1
        results:
          type: array
          items:
            $ref: '#/components/schemas/MovieListItem'
        total_pages:
          type: integer
          format: int32
          minimum: 1
          maximum: 500
          default: 1
        total_results:
          type: integer
          format: int32
          minimum: 0
          maximum: 10000
          default: 0
      required:
        - page
        - results
        - total_pages
        - total_results
    MovieListPageWithDates:
      allOf:
        - type: object
          properties:
            dates:
              type: object
              properties:
                maximum:
                  type: string
                  format: date
                minimum:
                  type: string
                  format: date
        - $ref: '#/components/schemas/MovieListPage'
    Object:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
        - id
        - name
    ObjectListPage:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 1
          maximum: 500
          default: 1
        results:
          type: array
          items:
            $ref: '#/components/schemas/Object'
        total_pages:
          type: integer
          format: int32
          minimum: 1
          maximum: 500
          default: 1
        total_results:
          type: integer
          format: int32
          minimum: 0
          maximum: 10000
          default: 0
      required:
        - page
        - results
        - total_pages
        - total_results
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
