openapi: 3.0.3
info:
  title: TMDB API
  description: The Movie Database (TMDB) API
  version: 0.32.0
servers:
  - url: https://api.themoviedb.org/3
    description: Main (production) server
  - url: https://api.themoviedb.localhost
    description: Internal staging server for testing
security:
  - bearerAuth: []
tags:
  - name: Configuration
  - name: Genre
  - name: Keywords
paths:
  /configuration/countries:
    get:
      summary: Countries
      description: Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
      operationId: ConfigurationCountries
      tags:
        - Configuration
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
                example:
                  - iso_3166_1: GB
                    english_name: United Kingdom
                    native_name: United Kingdom
                  - iso_3166_1: US
                    english_name: United States of America
                    native_name: United States
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
  /genre/movie/list:
    get:
      summary: Movie List
      description: Get the list of official genres for movies.
      operationId: GenreMovieList
      tags:
        - Genre
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenreList'
              example:
                genres:
                  - id: 12
                    name: Adventure
                  - id: 14
                    name: Fantasy
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
  /genre/tv/list:
    get:
      summary: TV List
      description: Get the list of official genres for TV shows.
      operationId: GenreTvList
      tags:
        - Genre
      parameters:
        - $ref: '#/components/parameters/LanguageParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenreList'
              example:
                genres:
                  - id: 10759
                    name: Action & Adventure
                  - id: 10765
                    name: Sci-Fi & Fantasy
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
  /keyword/{keyword_id}:
    get:
      summary: Details
      description: '---'
      operationId: KeywordDetails
      tags:
        - Keywords
      parameters:
        - $ref: '#/components/parameters/KeywordID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseObject'
              example:
                id: 1701
                name: hero
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
components:
  schemas:
    CountryCode:
      type: string
      description: |
        [ISO 3166-1 alpha-2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
      minLength: 2
      maxLength: 2
      pattern: ^[A-Z]{2}$
    Country:
      type: object
      additionalProperties: false
      required:
        - iso_3166_1
        - english_name
      properties:
        iso_3166_1:
          $ref: '#/components/schemas/CountryCode'
        english_name:
          type: string
        native_name:
          type: string
    Error:
      type: object
      additionalProperties: false
      required:
        - success
        - status_code
        - status_message
      properties:
        success:
          type: boolean
        status_code:
          type: integer
          format: int32
          minimum: 1
          maximum: 47
        status_message:
          type: string
    BaseObject:
      type: object
      description: The most generic type of item.
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
          description: |
            The identifier property represents any kind of identifier for any kind of [Thing](https://schema.org/Thing), such as ISBNs, GTIN codes, UUIDs etc.
        name:
          type: string
    GenreList:
      type: object
      description: A list of genres
      required:
        - genres
      properties:
        genres:
          type: array
          items:
            $ref: '#/components/schemas/BaseObject'
  parameters:
    LanguageParam:
      in: query
      name: language
      description: '`ISO-639-1`-`ISO-3166-1` code'
      schema:
        type: string
        minLength: 2
        maxLength: 5
        pattern: ^([a-z]{2})-([A-Z]{2})$
        default: en-US
    KeywordID:
      in: path
      name: keyword_id
      description: The keyword ID.
      required: true
      schema:
        type: integer
        format: int32
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    401Unauthorized:
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            status_code: 7
            status_message: 'Invalid API key: You must be granted a valid key.'
    429TooManyRequests:
      description: Too many requests in a given amount of time (“rate limiting”).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            status_code: 25
            status_message: Your request count is over the allowed limit.
    404NotFound:
      description: The server can not find the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            status_code: 34
            status_message: The resource you requested could not be found.
